version: "3"

services:
  db:
    container_name: live-music-db
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    container_name: live-music-redis
    image: redis

  app: &app_base
    container_name: live-music-app
    build: .
    volumes:
      - ./log:/usr/src/live-music/log
      - ./tmp:/usr/src/live-music/tmp
    env_file:
      - app.local.env
      - app.secret.env
    command: bin/start
    expose:
      - "3000"

  job:
    <<: *app_base
    container_name: live-music-job
    command: bundle exec sidekiq
    expose: []

  web:
    <<: *app_base
    container_name: live-music-web
    volumes:
      - ./shared/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    entrypoint: /usr/src/live-music/config/nginx/entrypoint.sh
    tty: true

  api:
    container_name: live-music-api
    image: node
    volumes:
      - ./config/api/entrypoint.sh:/entrypoint.sh
    environment:
      - PORT=18685
    ports:
      - "18685:18685"
    entrypoint: /entrypoint.sh
    command: node app.js