version: "3"

services:
  db:
    container_name: live-music-db
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    container_name: live-music-redis
    image: redis

  app: &app_base
    container_name: live-music-app
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./docker:/usr/src/live-music
    command: /usr/src/live-music/bin/start
    expose:
      - "3000"

  job:
    <<: *app_base
    container_name: live-music-job
    depends_on:
      - app
    command: bundle exec sidekiq
    expose: []

  web:
    container_name: live-music-web
    image: nginx
    depends_on:
      - app
    volumes:
      - ./docker/config/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./docker/public:/usr/src/live-music/public
      - ./docker/bin/install-ssl:/usr/src/live-music/bin/install-ssl
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_DOMAIN=example.com
      - CERTBOT_EMAIL=example@example.com

  api:
    container_name: live-music-api
    image: node
    depends_on:
      - app
    environment:
      - PORT=18685
    volumes:
      - ./docker/bin/start-api:/usr/src/live-music/bin/start-api
    command: /usr/src/live-music/bin/start-api
    ports:
      - "18685:18685"