version: "3.8"

services:
  db:
    container_name: live-music-db
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    container_name: live-music-redis
    image: redis

  app: &app_base
    container_name: live-music-app
    build: .
    volumes:
      - .:/usr/src/live-music
    command: bin/start

  job:
    <<: *app_base
    container_name: live-music-job
    command: bundle exec sidekiq

  web:
    container_name: live-music-web
    image: nginx
    volumes:
      - .:/usr/src/live-music
    ports:
      - "80:80"
      - "443:443"

  api:
    container_name: live-music-api
    image: node
    environment:
      - PORT=18685
    command:
      - git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git
      - cd NeteaseCloudMusicApi
      - npm install
      - node app.js
    ports:
      - "18685:18685"