version: "3"

services:
  db:
    container_name: live-music-db
    image: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    container_name: live-music-redis
    image: redis

  app: &app_base
    container_name: live-music-app
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./log:/usr/src/live-music/log
      - ./tmp:/usr/src/live-music/tmp
    command: bin/start
    expose:
      - "3000"

  job:
    <<: *app_base
    container_name: live-music-job
    depends_on:
      - app
    command: bundle exec sidekiq
    expose: []

  web:
    <<: *app_base
    container_name: live-music-web
    depends_on:
      - app
    volumes:
      - ./shared/ssl:/root/ssl
      - ./config/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./public:/usr/src/live-music/public
      - ./bin/install-ssl:/usr/src/live-music/bin/install-ssl
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_DOMAIN=example.com
      - CERTBOT_EMAIL=example@example.com
    command: bash -c "
        envsubst < /usr/src/live-music/config/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf &&
        /usr/src/live-music/bin/setup-ssl &&
        nginx
      "

  api:
    container_name: live-music-api
    image: node
    depends_on:
      - app
    environment:
      - PORT=18685
    command: bash -c "
        if ! [ -d NeteaseCloudMusicApi ]; then git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git; fi &&
        cd NeteaseCloudMusicApi &&
        npm install &&
        node app.js
      "
    ports:
      - "18685:18685"
