default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: live_music_production

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
